import { useLocation, Link } from "wouter";
import { useQueryClient } from "@tanstack/react-query";
import { useDeviceId } from "@/hooks/use-device-id";
import { 
  useListSchedules, 
  useDeleteSchedule,
  getListSchedulesQueryKey
} from "@workspace/api-client-react";
import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast";
import { Trash2, History as HistoryIcon, Calendar, ArrowRight } from "lucide-react";
import { format, formatDistanceToNow } from "date-fns";

export default function History() {
  const deviceId = useDeviceId();
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: schedules, isLoading } = useListSchedules(
    { deviceId: deviceId || "" },
    { query: { enabled: !!deviceId, queryKey: getListSchedulesQueryKey({ deviceId: deviceId || "" }) } }
  );

  const deleteSchedule = useDeleteSchedule();

  const handleDelete = (id: string, e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (!deviceId) return;
    
    deleteSchedule.mutate(
      { id },
      {
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: getListSchedulesQueryKey({ deviceId }) });
          toast({ title: "Schedule deleted" });
        },
        onError: (err: any) => {
          toast({ title: "Error", description: err?.data?.message, variant: "destructive" });
        }
      }
    );
  };

  if (!deviceId || isLoading) {
    return (
      <Layout>
        <div className="space-y-6 pt-8">
          <Skeleton className="h-10 w-48" />
          <div className="grid gap-4">
            <Skeleton className="h-24 w-full rounded-xl" />
            <Skeleton className="h-24 w-full rounded-xl" />
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="max-w-4xl mx-auto space-y-8 pt-8">
        <header className="space-y-1">
          <h1 className="text-3xl font-heading font-semibold tracking-tight text-foreground flex items-center gap-3">
            <HistoryIcon className="w-8 h-8 text-primary" />
            History
          </h1>
          <p className="text-muted-foreground text-lg">
            Past schedules generated by AI.
          </p>
        </header>

        {schedules && schedules.length > 0 ? (
          <div className="grid gap-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {schedules.map((schedule) => (
              <Link key={schedule.id} href={`/schedule/${schedule.id}`}>
                <a className="block group">
                  <div className="bg-card border rounded-xl p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-all hover:shadow-md hover:border-primary/40 cursor-pointer">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-secondary rounded-lg flex items-center justify-center text-muted-foreground group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                        <Calendar className="w-6 h-6" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <h3 className="font-semibold text-lg capitalize">{schedule.scope} Schedule</h3>
                          <Badge variant={schedule.status === "complete" ? "default" : "secondary"}>
                            {schedule.status === "complete" ? "Ready" : "Draft"}
                          </Badge>
                        </div>
                        <p className="text-sm text-muted-foreground">
                          Created {format(new Date(schedule.createdAt), "MMM d, yyyy")} • {formatDistanceToNow(new Date(schedule.createdAt))} ago
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2 self-end sm:self-auto">
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button 
                            variant="ghost" 
                            size="icon" 
                            className="text-muted-foreground hover:text-destructive hover:bg-destructive/10 z-10"
                            onClick={(e) => e.stopPropagation()}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent onClick={(e) => e.stopPropagation()}>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Delete schedule?</AlertDialogTitle>
                            <AlertDialogDescription>
                              This will permanently delete this schedule from your history.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction onClick={(e) => handleDelete(schedule.id, e as any)} className="bg-destructive text-destructive-foreground">
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                      
                      <div className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center text-muted-foreground group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                        <ArrowRight className="w-4 h-4" />
                      </div>
                    </div>
                  </div>
                </a>
              </Link>
            ))}
          </div>
        ) : (
          <div className="bg-card border rounded-2xl p-12 text-center shadow-sm">
            <div className="w-16 h-16 bg-secondary text-muted-foreground rounded-2xl flex items-center justify-center mx-auto mb-6">
              <HistoryIcon className="w-8 h-8" />
            </div>
            <h2 className="text-xl font-medium mb-2">No history yet</h2>
            <p className="text-muted-foreground mb-6">
              You haven't generated any schedules yet. Go to Plan to create your first one.
            </p>
            <Button asChild>
              <Link href="/generate">Go to Plan</Link>
            </Button>
          </div>
        )}
      </div>
    </Layout>
  );
}
