kind = "mobile"
previewPath = "/mobile/"
title = "Tempus Mobile"
version = "1.0.0"
id = "artifacts/tempus-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 20833

[services.development]
run = "pnpm --filter @workspace/tempus-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tempus-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/tempus-mobile", "run", "serve" ]

[services.env]
PORT = "20833"
BASE_PATH = "/mobile/"
